nome = input("Entre com seu nome: ")
cpf = input("Entre com seu CPF: ")
endereco = input("Entre com seu endereço: ")
idade = input("Entre com sua idade: ")
altura = input("Entre com sua altura: ")
tel = input("Entre com seu telefone: ")

# print("Nome:",nome,"\tCPF:",cpf,"\tEndereço:",endereco,"\tIdade:",idade,"\tAltura:",altura,"\tTelefone:",tel)
print("Nome:\t",nome)
print("CPF:\t",cpf)
print("Endereço:\t",endereco)
print("idade:\t",idade,"anos")
print("Altura:\t",altura,"metros")
print("Telefone:\t",tel)
