from veiculo import Veiculo
from carro import Carro

caminhao_rosa = Veiculo("rosa", 6, "Ford", 10)
print(caminhao_rosa)
print(type(caminhao_rosa))
print("CAMINHAO ROSA")
print("Cor:", caminhao_rosa.cor)
print("Marca:", caminhao_rosa.marca)
print("Quantidade de rodas:", caminhao_rosa.qtd_rodas)
print("Tanque:", caminhao_rosa.tanque, "litros")
print("=====================================")
carro_azul = Carro("azul", "BMW", 30)
print("CARRO AZUL")
print("Cor:", carro_azul.cor)
print("Marca:", carro_azul.marca)
print("Quantidade de rodas:", carro_azul.qtd_rodas)
print("Tanque:", carro_azul.tanque, "litros")
carro_azul.abastecer(35)
print("Tanque:", carro_azul.tanque, "litros")